### ISSUE TITLE
New-CyConsoleConfig Error

### ISSUE THREAD

**Issue by GQnzo** [jan-tee/cycli#3]
I'm attempting to use New-CyConsoleConfig but there is an error. I have validated that my API ID, Secret, and Tenant ID are correct as they work in my Python script. Someone on my team suggested that it may be the region that is broken. (*** added for privacy)

`
PS C:\Users\*******> New-CyConsoleConfig

cmdlet New-CyConsoleConfig at command pipeline position 1
Supply values for the following parameters:
Console: *******
APIId: ***********************
APISecret: *
APITenantId: *********************
Region: us
Get-CyAPI : System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Program Files\WindowsPowerShell\Modules\cycli\0.7.0\CyHelper.ps1:164 char:21
+ ...     $null = Get-CyAPI -APIId $APIId -APISecret $APISecret -APITenantI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI

Get-CyAPI : Could not obtain valid API token. This may mean that (a) your API credentials are incorrect or (b) your API auth URL is incorrect (use
Get-Help Get-CyAPI to get a list of URLs), and your code is attempting to authenticate to the wrong global API instance.
At C:\Program Files\WindowsPowerShell\Modules\cycli\0.7.0\CyHelper.ps1:164 char:21
+ ...     $null = Get-CyAPI -APIId $APIId -APISecret $APISecret -APITenantI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CyAPI

The remote server returned an error: (401) Unauthorized.`

**Comment by GQnzo** [comment]
Never mind. It was user error.
